#!/bin/sh

set -e

GRAFANA_JS=/srv/grafana/config.js

sed s/{{ELASTICSEARCH_HOST}}/${ELASTICSEARCH_HOST}/ ${GRAFANA_JS} > ${GRAFANA_JS}
sed s/{{ELASTICSEARCH_PORT}}/${ELASTICSEARCH_PORT}/ ${GRAFANA_JS} > ${GRAFANA_JS}
sed s/{{ELASTICSEARCH_INDEX}}/${ELASTICSEARCH_INDEX}/ ${GRAFANA_JS} > ${GRAFANA_JS}

sed s/{{GRAPHITE_HOST}}/${GRAPHITE_HOST}/ ${GRAFANA_JS} > ${GRAFANA_JS}
sed s/{{GRAPHITE_PORT}}/${GRAPHITE_PORT}/ ${GRAFANA_JS} > ${GRAFANA_JS}
